### ISSUE TITLE
secsonserver * initial connection timestamp bug?

### ISSUE THREAD

**Issue by LindenCX** [nhnkl159/SimpleStats#1]
Hi,

Odd issue, I compiled this plugin a few days ago for a couple of our retake servers, the kill tracking and all works fine. 

But the secsonserver and the unix timestamp seem to be bugged. Every user has the same connection time no matter when they connected, and the secsonserver is extremely high for some users. 

Screenshot: 
![uhh](https://user-images.githubusercontent.com/2645951/28843141-1f0a3712-76ce-11e7-981b-2fc68ce0dcbe.png)

Any clue what might be causing this?

**Comment by nhnkl159** [comment]
I updated and fixed the problem with the lastconn , but I can't see any problem with the secsonserver , please keep in mind that those are seconds and for example 310917 seconds = 3 days.

**Comment by LindenCX** [comment]
Thanks, the server reporting to that table has only been up 24 hours. (and i'm pretty sure that Throne guy just joined and left)

**Comment by LindenCX** [comment]
I cleared the timestamps and secsonserver in the database, then fired up the newest version. 

Timestamps are fixed, something still odd with the seconds. 

screenshot: http://i.imgur.com/zd8sGXJ.png

the guy at the very top connected for a couple minutes then left.

**Comment by gegeorgege37** [comment]
At `void FuckingUpdateThatSHITHeadPlayer(int client, float timeonserver)` change `int gB_Seconds = RoundToZero(timeonserver);` with `int gB_Seconds = RoundToNearest(timeonserver);`

Worked well for me.

**Comment by nhnkl159** [comment]
@gegeorgege37 
Thanks for the fix, updated my plugin.

**Comment by LindenCX** [comment]
That still doesn't appear to have fixed it on my side. I will however note one thing, when I run a server with it's own separate database, the secsonserver issue doesn't happen.

When I run multiple servers on the same database the seconserver seem to spike. I can literally refresh the phpmyadmin page showing the table, and watch each person's seconds go up by like 300 each time I refresh. (every 1-2 seconds)
